### ISSUE TITLE
Changes in the timing of the Open Community Working Meetings

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/TSC#12]
## Context
I'd like to suggest changing the current time of the Open Community Working Meetings to make it more accessible for Community Members based in European Countries different from the UK and potentially Asian Countries. In my case (Spain) the meeting is happening at 23:00 which is inconvenient. 

## Proposal
For this reason, I'd like to suggest changing the timing of the Open Community Working Meeting to start 2 hours earlier: at 20 BST instead of 22 BST.

![Screenshot 2024-09-10 at 10 46 48](https://github.com/user-attachments/assets/e8758c20-9ef6-43bf-a2a1-c104f9889655)

## Call to Vote or alternatives.
Please signal your vote to proceed with this new proposal by reacting to the comment below or suggesting other alternatives.

**Comment by benjagm** [comment]
Please signal your vote to proceed with this new proposal.

👍 In Favour
👎 Against

**Comment by gregsdennis** [comment]
This is going to change in a few weeks anyway.  What's currently 9am for me (NZ) will be 11am.  (NZ slides forward 1h, SFO slides back 1h.)

This is just because we're southern hemisphere, though.  Australia would be in the same boat.  But others won't really be affected.

**Comment by jviotti** [comment]
I'm in between the team's trickiest timezones so any time will likely work for me!

**Comment by benjagm** [comment]
With FOUR votes in favour we proceed with this proposal. Thanks everyone!
