### ISSUE TITLE
Propose Benja Granados as a new member of the TSC

### ISSUE THREAD

**Issue by jdesrosiers** [json-schema-org/TSC#13]
## Reason for vote

I would like to propose adding Benja Granados (@benjagm) to the TSC.

I call for a vote from the TSC as per our governance process of [decision making via vote](https://github.com/json-schema-org/community/blob/main/GOVERNANCE.md#decision-making-via-vote), for which I will create a comment in this issue. Note that our policy is that votes will close after 7 days and we must reach a 75% quorum for the vote to carry.

## About Benja

Benja has been JSON Schema's community manager for about two years and has developed an expertise JSON Schema in that time. He has proposed, championed, and implemented most of the initiatives that have been introduced in the last couple years including a new website, the ambassador program, GSoC/D, and much more. Benja's role as community manager and his greater experience in developer relations gives him a perspective that would be valuable to the TSC. Most of us have implementations we maintain which can bias our views toward what we need or want. Benja can be an unbiased voice for community. Benja also brings a background in software engineering, leadership, APIs and API governance, and connections with JSON Schema related projects like AsyncAPI.

**Comment by jdesrosiers** [comment]
Please signal your vote by for Benja Granados to be invited to join the TSC by reacting to this comment.

👍 In Favour
👎 Against
😕 Request 7 day extension

**Comment by benjagm** [comment]
With 6 votes in favour of a total of 8 we proceed with this proposal. Thanks everyone!
