### ISSUE TITLE
Proposal to create a Triage Team. First steps for a more open and accesible governance model.

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/TSC#14]
## Context
For the last 2 years, we have increased the number of regular contributors to supporting projects in our organization like the website, landscape, and ecosystem. However, our governance model still has a huge gap between the leadership roles like TSC or Maintainers and regular contributors. In addition, we don't have a written process explaining how to become a maintainer of a project or TSC member. This can lead to issues in scaling the project.

## Proposal
As a first step, I'd like to set up a team called **Triage Team** for regular users interested in helping with issue triage in those supporting projects. Of course, this proposal does not affect the spec repository, as the spec has is own governance process.

## Call to Vote or alternatives.
Please signal your vote to proceed with this new proposal by reacting to the comment below or suggesting other alternatives.

**Comment by benjagm** [comment]
Please signal your vote to proceed with this new proposal.

👍 In Favour
👎 Against

**Comment by mwadams** [comment]
I think this is a good idea.

It is really important to educate people on the triage team about tone-of-voice and speaking for the project (especially when communicating in a language which is not your primary).

I have dealt with triage teams on other projects and the experience has varied from encouraging and supportive to rude and superior.

**Comment by benjagm** [comment]
> It is really important to educate people on the triage team about tone-of-voice and speaking for the project (especially when communicating in a language which is not your primary).

Great point Matthew! If approved, we can create a Triage Team guide and maybe a video recording with the tips required to do a great job on this role.

**Comment by gregsdennis** [comment]
I like the idea, but I would want it limited to specify repos and discussions.  For instance, I'm not sure I'm ready to let non-maintainers triage spec issues.

**Comment by benjagm** [comment]
> I like the idea, but I would want it limited to specify repos and discussions. For instance, I'm not sure I'm ready to let non-maintainers triage spec issues.

100% on this. The spec should not be part of the scope of this group. This is just for secondary projects like website, tour or landscape.

**Comment by benjagm** [comment]
With FOUR votes in favour, we proceed with this proposal. Thanks everyone!
