### ISSUE TITLE
500$ Travel stipend to support JSON Conference Speakers

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/TSC#15]
## Context
This is the first JSON Schema Conference and we need to make it a huge success. Supporting Speakers is one of the best ways to make that happen, however API Days does not provide financial support for Speakers. We tried to attract Sponsors to get resources to cover the Conference expenses and support speakers but haven't had success so far.

## Proposal
I'd like to use our funds to pay a 500$ travel stipend to support the Conference's Speakers.

## Call to Vote or alternatives.
Please signal your vote to proceed with this new proposal by reacting to the comment below or suggesting other alternatives.

**Comment by benjagm** [comment]
Please signal your vote to proceed with this new proposal.

👍 In Favour
👎 Against

**Comment by gregsdennis** [comment]
Is this $500 per speaker?

**Comment by benjagm** [comment]
> Is this $500 per speaker?

Yes. It won't cover all the expenses but depending on the origin location, maybe most of them.

**Comment by jviotti** [comment]
Any support is great!

**Comment by mwadams** [comment]
(And endjin would be paying for me should I be speaking so that saves a few bob!)

**Comment by benjagm** [comment]
With SEVEN votes in favour, we proceed with this proposal. Thanks everyone!

**Comment by jviotti** [comment]
@benjagm Do we have a process in place for how/when the stipend will be paid?

**Comment by benjagm** [comment]
> @benjagm Do we have a process in place for how/when the stipend will be paid?

Yes we have. Please join the speakers channel in slack to see all the details [#temp-json-schema-conf-speakers](https://json-schema.slack.com/archives/C0800GX3P4Y)
