### ISSUE TITLE
Tour of JSON Schema - Maintainer Nomination

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/TSC#18]
## Context
As discussed in the last OCWM (https://github.com/json-schema-org/community/issues/803), we need to provide processes to enable active contributors to step up their commitment to the project.  This is why initiatives like the Triage Team and allowing active contributors to become maintainers of peripheral projects are very important for project sustainability.

## Proposal
I'd like to nominate @JeelRajodiya to officially become the maintainer of the Tour of JSON Schema, a role that unofficially has been playing since the beginning of that project as he has fully developed it as part of GSoC. Special call out to his mentor @erosb.

## Call to Vote or alternatives.
Please signal your vote to proceed with this new proposal by reacting to the comment below or suggesting other alternatives.

**Comment by benjagm** [comment]
Please signal your vote reacting to this comment.

👍 In Favour
👎 Against

**Comment by erosb** [comment]
Sure, go ahead with making it official :)

**Comment by benjagm** [comment]
With 5 votes in favour, we proceed with this proposal. Thanks everyone!
