### ISSUE TITLE
Call for votes: GSoC - Stipend for mentors not being paid full time to work on the project

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/TSC#3]
As part of GSoC, [JSON Schema will receive a $500 stipend per contributor (often called the organization stipend)](https://developers.google.com/open-source/gsoc/help/org-payments). This will be a great opportunity to have additional funds to support our current initiatives but specially it will give us the chance to use those stipends to cool things like strengthen the mentoring strategy.

With that in mind I'd like to propose that mentors that are not being paid to work full time on the project will get that 500$ stipend per project. I think is important to provide this kind of incentives if we like to build trust with among our community and get more people interested next years.

I'd like to ask the TSC to vote to support or reject this proposal.  Please use reactions to vote.

(Discussed in Open Community Working Meeting 2024-03-11 https://github.com/json-schema-org/community/issues/662)

See voting process [here](https://github.com/json-schema-org/community/blob/main/GOVERNANCE.md#decision-making-via-vote).

**Comment by benjagm** [comment]
Closed as completed.

**Comment by Relequestual** [comment]
My apologies, we do not have in place automations to notify into slack, per the governance document.

Vote meets quorum threshold.
Vote meets time requirements.
Votes are 4 TSC members in favour.
