### ISSUE TITLE
Call for votes: Swag budget approval

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/TSC#4]
### Context

This issue is to ask the TSC for vote to approve/reject the Swag budget detailed in this issue: https://github.com/json-schema-org/community/issues/678. I'd like to have the swag ready as a pre-requisite to launch the Ambassadors Program. 

Dear TSC members, please vote to support or reject this proposal. (Please use reactions to vote)

(Discussed in Open Community Working Meeting 2024-04-08 https://github.com/json-schema-org/community/issues/688)

See voting process [here](https://github.com/json-schema-org/community/blob/main/GOVERNANCE.md#decision-making-via-vote).

**Comment by karenetheridge** [comment]
Not to be too pendantic about it, but the voting process says "The votes will be collected by way of using GitHub Reactions on a specific comment, which must not be the first comment."

**Comment by benjagm** [comment]
Dear TSC members, please vote to support or reject this proposal. (Please use reactions to this comment to vote)

**Comment by benjagm** [comment]
> The votes will be collected by way of using GitHub Reactions on a specific comment, which must not be the first comment

Thank Karen. You are right! Just added the comment.

**Comment by benjagm** [comment]
After looking into the possible delivery and customs costs of this approach I just created a new proposal focused on using a global print-on-demand partner and Shopify with the result of 50% costs reduction.

Please vote again using this issue #8

**Comment by benjagm** [comment]
This is the result of the vote:
- Vote meets quorum threshold.
- Vote meets time requirements.
- Votes are 5 TSC members in favour.
